language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: gdgct-devfest18
  token:
    secure: HK4m1O7sBL0qxR+ND5hiMkmqDG0Nu4khDVPg8Gm5pwf/peorVnOBb8wM+0wi8fc0riRc7OH47VVSgbkJ0m5WSdpn+t+4IFQN7cZ4TxGis9EM4u2ZcDQliFo4t8kRtxZ9bn6jvWmlkORhxnWkRkYRCZxBdgjTNjVanPLCX/uy0icqDb7uOQRsbcQcZlRelE/U+rWo0dDouAKy3jFL1u/mTZ04lUx6dRVkrmiJYgflqUWYs0cI14b6xmqCJ27jZokvbmE0g+v9szoX0dLvfdlfZFdMDSuvS0DwEoBqbNvDmL/WjRCSP2a49d4gAbm3rF1+RmC0GKYfkTx7AutXTOM1SVekFhSfqbhG9vDSLi4R2TKciLm8FY86GNFHDTal88unQWsGuxdKOCWB7JcBHaNqmOFhtHx61kWwbSHOo9+AadnjgS0p1jLoxSBFbNNtj1YVncokasnnhmCpLCwUZHR1v1k9qoLzJB6V+PJr7WEdwttiUAHmWqS7J0aP9on4EmsDScdwLK1r3cz4WoC/5AQwCXhPYUgj7c3M8eHJm+lZqVpgKkR6vtERlKCP0B3PDrH3wybmRyj689vy3OEPcSgVw4vcVPJdtzZC4nv+cvL3MP1xgAkCVbOP5DstSF25HSRYbvTEetMAecP+3hDCX0Z/WsQegSxHurOMFdHDT2/FEtk=
